import {
  Activity,
  AlertTriangle,
  ArrowLeftRight,
  BarChart,
  BarChart2,
  BarChart3,
  BookOpen,
  Bot,
  Brain,
  Bug,
  Calendar,
  CalendarDays,
  Clock,
  Code,
  Coins,
  Container,
  Cpu,
  Database,
  FileBarChart,
  FileText,
  Fish,
  Gauge,
  Globe,
  HardDrive,
  Hash,
  HeartPulse,
  Leaf,
  ListChecks,
  Mail,
  MemoryStick,
  MessageCircle,
  MessageSquare,
  Newspaper,
  PenLine,
  PieChart,
  Rocket,
  Rss,
  Search,
  Send,
  Server,
  Shield,
  Sheet,
  Sparkles,
  Table,
  Target,
  TrendingUp,
  User,
  Wallet,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const SKILL_ICON_MAP: Record<string, LucideIcon> = {
  search: Search,
  rss: Rss,
  newspaper: Newspaper,
  globe: Globe,
  "book-open": BookOpen,
  github: Bot,
  "heart-pulse": HeartPulse,
  shield: Shield,
  calendar: Calendar,
  gauge: Gauge,
  "bar-chart": BarChart,
  "pen-line": PenLine,
  "message-circle": MessageCircle,
  "trending-up": TrendingUp,
  "calendar-days": CalendarDays,
  "bar-chart-2": BarChart2,
  bug: Bug,
  code: Code,
  "alert-triangle": AlertTriangle,
  rocket: Rocket,
  "file-text": FileText,
  server: Server,
  cpu: Cpu,
  "memory-stick": MemoryStick,
  "hard-drive": HardDrive,
  activity: Activity,
  container: Container,
  wallet: Wallet,
  coins: Coins,
  fish: Fish,
  "arrow-left-right": ArrowLeftRight,
  sparkles: Sparkles,
  "pie-chart": PieChart,
  table: Table,
  sheet: Sheet,
  database: Database,
  "file-bar-chart": FileBarChart,
  "bar-chart-3": BarChart3,
  send: Send,
  "message-square": MessageSquare,
  mail: Mail,
  hash: Hash,
  brain: Brain,
  "list-checks": ListChecks,
  target: Target,
  clock: Clock,
  user: User,
  zap: Zap,
  leaf: Leaf,
};

export function getSkillIcon(name: string): LucideIcon {
  return SKILL_ICON_MAP[name] ?? Zap;
}
