-- AlterTable
ALTER TABLE "AgentRun" ADD COLUMN "inputTokens" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "AgentRun" ADD COLUMN "outputTokens" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "AgentRun" ADD COLUMN "estimatedCostUsd" DOUBLE PRECISION NOT NULL DEFAULT 0;
