ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "fallbackModels" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "agentMemoryEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "agentMemoryUrl" TEXT;
