export const SKILL_CATEGORIES = [
  "Research",
  "Website",
  "Social",
  "Developer",
  "DevOps",
  "Crypto",
  "Data",
  "Notification",
  "Agent Core",
] as const;

export const ALL_SKILL_DEFINITIONS = [
  { slug: "web-search", name: "Web Search", category: "Research", description: "Search the web for information.", icon: "search", isEnabled: true },
  { slug: "rss-reader", name: "RSS Reader", category: "Research", description: "Fetch and parse RSS feeds.", icon: "rss", isEnabled: true },
  { slug: "news-monitor", name: "News Monitor", category: "Research", description: "Monitor news sources for topics.", icon: "newspaper", isEnabled: true },
  { slug: "website-scraper", name: "Website Scraper", category: "Research", description: "Extract content from web pages.", icon: "globe", isEnabled: true },
  { slug: "documentation-reader", name: "Documentation Reader", category: "Research", description: "Read and summarize documentation.", icon: "book-open", isEnabled: true },
  { slug: "github-repo-analyzer", name: "GitHub Repo Analyzer", category: "Research", description: "Analyze GitHub repositories.", icon: "github", isEnabled: true },
  { slug: "website-health-check", name: "Website Health Check", category: "Website", description: "Check website uptime and response time.", icon: "heart-pulse", isEnabled: true },
  { slug: "ssl-monitor", name: "SSL Monitor", category: "Website", description: "Monitor SSL certificate expiry.", icon: "shield", isEnabled: true },
  { slug: "domain-expiry-monitor", name: "Domain Expiry Monitor", category: "Website", description: "Track domain expiration dates.", icon: "calendar", isEnabled: true },
  { slug: "performance-audit", name: "Performance Audit", category: "Website", description: "Run performance audits on websites.", icon: "gauge", isEnabled: true },
  { slug: "seo-audit", name: "SEO Audit", category: "Website", description: "Analyze SEO metrics for websites.", icon: "bar-chart", isEnabled: true },
  { slug: "x-draft-generator", name: "X Draft Generator", category: "Social", description: "Generate X post drafts.", icon: "pen-line", isEnabled: true },
  { slug: "x-thread-drafter", name: "X Thread Drafter", category: "Social", description: "Generate multi-tweet thread drafts.", icon: "pen-line", isEnabled: true },
  { slug: "x-post", name: "X Post", category: "Social", description: "Post to X when auto-post is enabled.", icon: "send", isEnabled: true },
  { slug: "x-profile-lookup", name: "X Profile Lookup", category: "Social", description: "Look up an X user profile by username.", icon: "user", isEnabled: true },
  { slug: "x-timeline-reader", name: "X Timeline Reader", category: "Social", description: "Read recent tweets from an X user.", icon: "rss", isEnabled: true },
  { slug: "reply-generator", name: "Reply Generator", category: "Social", description: "Generate reply drafts.", icon: "message-circle", isEnabled: true },
  { slug: "viral-topic-finder", name: "Viral Topic Finder", category: "Social", description: "Find trending topics.", icon: "trending-up", isEnabled: true },
  { slug: "content-calendar", name: "Content Calendar", category: "Social", description: "Plan content schedules.", icon: "calendar-days", isEnabled: true },
  { slug: "engagement-analyzer", name: "Engagement Analyzer", category: "Social", description: "Analyze social engagement.", icon: "bar-chart-2", isEnabled: true },
  { slug: "github-reader", name: "GitHub Reader", category: "Developer", description: "Read GitHub issues and PRs.", icon: "github", isEnabled: true },
  { slug: "issue-assistant", name: "Issue Assistant", category: "Developer", description: "Assist with issue triage.", icon: "bug", isEnabled: true },
  { slug: "code-review-assistant", name: "Code Review Assistant", category: "Developer", description: "Review code changes.", icon: "code", isEnabled: true },
  { slug: "error-analyzer", name: "Error Analyzer", category: "Developer", description: "Analyze error logs and stack traces.", icon: "alert-triangle", isEnabled: true },
  { slug: "deployment-monitor", name: "Deployment Monitor", category: "Developer", description: "Monitor deployment status.", icon: "rocket", isEnabled: true },
  { slug: "log-reader", name: "Log Reader", category: "Developer", description: "Parse and analyze log files.", icon: "file-text", isEnabled: true },
  { slug: "vps-monitor", name: "VPS Monitor", category: "DevOps", description: "Monitor VPS health.", icon: "server", isEnabled: true },
  { slug: "cpu-monitor", name: "CPU Monitor", category: "DevOps", description: "Track CPU usage.", icon: "cpu", isEnabled: true },
  { slug: "ram-monitor", name: "RAM Monitor", category: "DevOps", description: "Track memory usage.", icon: "memory-stick", isEnabled: true },
  { slug: "disk-monitor", name: "Disk Monitor", category: "DevOps", description: "Track disk usage.", icon: "hard-drive", isEnabled: true },
  { slug: "pm2-monitor", name: "PM2 Monitor", category: "DevOps", description: "Monitor PM2 processes.", icon: "activity", isEnabled: true },
  { slug: "nginx-monitor", name: "Nginx Monitor", category: "DevOps", description: "Monitor Nginx status.", icon: "globe", isEnabled: true },
  { slug: "docker-monitor", name: "Docker Monitor", category: "DevOps", description: "Monitor Docker containers.", icon: "container", isEnabled: true },
  { slug: "solana-rpc-monitor", name: "Solana RPC Monitor", category: "Crypto", description: "Monitor Solana RPC health.", icon: "activity", isEnabled: true },
  { slug: "sol-price-checker", name: "SOL Price Checker", category: "Crypto", description: "Live SOL price in USD with 24h change.", icon: "coins", isEnabled: true },
  { slug: "token-price-tracker", name: "Token Price Tracker", category: "Crypto", description: "Live token price from DexScreener (mint address).", icon: "trending-up", isEnabled: true },
  { slug: "jupiter-price", name: "Jupiter Price", category: "Crypto", description: "Liquidity-weighted USD price via Jupiter aggregator.", icon: "trending-up", isEnabled: true },
  { slug: "rugcheck", name: "Rugcheck Safety", category: "Crypto", description: "Token rug-risk score, authorities, LP lock, risk flags.", icon: "shield", isEnabled: true },
  { slug: "token-finder", name: "Token Finder", category: "Crypto", description: "Resolve a ticker/name to a Solana mint address.", icon: "search", isEnabled: true },
  { slug: "sns-resolver", name: "SNS Domain Resolver", category: "Crypto", description: "Resolve a .sol domain to its owner wallet.", icon: "globe", isEnabled: true },
  { slug: "network-stats", name: "Solana Network Stats", category: "Crypto", description: "Live Solana TPS, epoch progress, validator version.", icon: "activity", isEnabled: true },
  { slug: "wallet-networth", name: "Wallet Net Worth", category: "Crypto", description: "Estimate a wallet's USD net worth from SOL holdings.", icon: "wallet", isEnabled: true },
  { slug: "token-quick-lookup", name: "Token Quick Lookup", category: "Crypto", description: "Paste CA or type ticker — instant price + safety.", icon: "zap", isEnabled: true },
  { slug: "trending-tokens", name: "Trending Tokens", category: "Crypto", description: "Top trending Solana tokens on DexScreener.", icon: "flame", isEnabled: true },
  { slug: "meme-coin-scanner", name: "AYRA Scan", category: "Crypto", description: "AYRA scan: meme coins with quality filters (MCAP, holders, rug score).", icon: "leaf", isEnabled: true },
  { slug: "token-quality-report", name: "AYRA Quality Report", category: "Crypto", description: "AYRA quality report for one mint (MCAP, holders, rug score).", icon: "shield", isEnabled: true },
  { slug: "wallet-tracker", name: "Wallet Tracker", category: "Crypto", description: "Track SOL balance and SPL tokens for a wallet.", icon: "wallet", isEnabled: true },
  { slug: "token-tracker", name: "Token Tracker", category: "Crypto", description: "Fetch on-chain mint info for a Solana token.", icon: "coins", isEnabled: true },
  { slug: "token-recommendation", name: "Token Research", category: "Crypto", description: "Dev-focused token briefing. Not financial advice.", icon: "trending-up", isEnabled: true },
  { slug: "whale-tracker", name: "Whale Tracker", category: "Crypto", description: "Track large wallet movements.", icon: "fish", isEnabled: true },
  { slug: "dex-monitor", name: "DEX Monitor", category: "Crypto", description: "Monitor DEX activity.", icon: "arrow-left-right", isEnabled: true },
  { slug: "new-token-monitor", name: "New Token Monitor", category: "Crypto", description: "Detect new token launches.", icon: "sparkles", isEnabled: true },
  { slug: "portfolio-tracker", name: "Portfolio Tracker", category: "Crypto", description: "Track crypto portfolio.", icon: "pie-chart", isEnabled: true },
  { slug: "csv-reader", name: "CSV Reader", category: "Data", description: "Read and parse CSV files.", icon: "table", isEnabled: true },
  { slug: "excel-reader", name: "Excel Reader", category: "Data", description: "Read Excel spreadsheets.", icon: "sheet", isEnabled: true },
  { slug: "database-query", name: "Database Query", category: "Data", description: "Query agent memories and runs.", icon: "database", isEnabled: true },
  { slug: "report-generator", name: "Report Generator", category: "Data", description: "Generate data reports.", icon: "file-bar-chart", isEnabled: true },
  { slug: "chart-generator", name: "Chart Generator", category: "Data", description: "Generate charts from data.", icon: "bar-chart-3", isEnabled: true },
  { slug: "image-generator", name: "Image Generator", category: "Social", description: "Generate images from text prompts via OpenRouter.", icon: "sparkles", isEnabled: true },
  { slug: "telegram-notify", name: "Telegram Notify", category: "Notification", description: "Send Telegram notifications.", icon: "send", isEnabled: true },
  { slug: "discord-notify", name: "Discord Notify", category: "Notification", description: "Send Discord notifications.", icon: "message-square", isEnabled: true },
  { slug: "email-notify", name: "Email Notify", category: "Notification", description: "Send email notifications.", icon: "mail", isEnabled: true },
  { slug: "slack-notify", name: "Slack Notify", category: "Notification", description: "Send Slack notifications.", icon: "hash", isEnabled: true },
  { slug: "memory-storage", name: "Memory Storage", category: "Agent Core", description: "Store agent memories.", icon: "brain", isEnabled: true },
  { slug: "memory-search", name: "Memory Search", category: "Agent Core", description: "Search agent memories.", icon: "search", isEnabled: true },
  { slug: "task-planner", name: "Task Planner", category: "Agent Core", description: "Plan multi-step tasks.", icon: "list-checks", isEnabled: true },
  { slug: "goal-tracker", name: "Goal Tracker", category: "Agent Core", description: "Track agent goals.", icon: "target", isEnabled: true },
  { slug: "scheduled-tasks", name: "Scheduled Tasks", category: "Agent Core", description: "Manage scheduled tasks.", icon: "clock", isEnabled: true },
  { slug: "brain-task-schedule", name: "Brain Task Schedule", category: "Agent Core", description: "Schedule persisted tweets, reminders, and calendar tasks.", icon: "calendar", isEnabled: true },
  { slug: "brain-task-list", name: "Brain Task List", category: "Agent Core", description: "List upcoming brain tasks.", icon: "list-checks", isEnabled: true },
  { slug: "brain-task-cancel", name: "Brain Task Cancel", category: "Agent Core", description: "Cancel a pending brain task.", icon: "clock", isEnabled: true },
  { slug: "brain-calendar-plan", name: "Brain Calendar Plan", category: "Social", description: "Plan and schedule a multi-day content calendar.", icon: "calendar-days", isEnabled: true },
  { slug: "arxiv-search", name: "arXiv Search", category: "Research", description: "Search arXiv research papers.", icon: "book-open", isEnabled: true },
  { slug: "news-digest", name: "News Digest", category: "Research", description: "Topic digest from web search for scheduled automations.", icon: "newspaper", isEnabled: true },
  { slug: "polymarket-search", name: "Polymarket Search", category: "Research", description: "Search prediction market odds on Polymarket.", icon: "bar-chart-2", isEnabled: true },
  { slug: "polymarket-trending", name: "Polymarket Trending", category: "Research", description: "Trending Polymarket events by volume.", icon: "trending-up", isEnabled: true },
  { slug: "github-issue-search", name: "GitHub Issue Search", category: "Developer", description: "Search issues in a GitHub repo.", icon: "github", isEnabled: true },
  { slug: "github-repo-info", name: "GitHub Repo Info", category: "Developer", description: "Repository metadata from GitHub API.", icon: "github", isEnabled: true },
];
