import { LegalPageLayout, legalMetadata } from "@/components/legal/legal-page-layout";

export const metadata = legalMetadata(
  "Terms of Service",
  "Terms and conditions for using AYRA Agent."
);

export default function TermsPage() {
  return (
    <LegalPageLayout title="Terms of Service" lastUpdated="June 22, 2025">
      <p>
        By accessing or using AYRA Agent, you agree to these Terms of Service. If you do not agree,
        do not use the platform.
      </p>

      <h2>1. Service description</h2>
      <p>
        AYRA Agent is a developer tool for building and running AI agents with skills, memory,
        schedules, and integrations (Solana research, X, Telegram, and more). It is designed for
        developer workflows — not automated trading or financial advice.
      </p>

      <h2>2. Eligibility</h2>
      <p>
        You must be at least 16 years old and able to form a binding contract. You are responsible
        for compliance with laws in your jurisdiction, including regulations related to social media,
        crypto, and data processing.
      </p>

      <h2>3. Your account</h2>
      <ul>
        <li>You are responsible for keeping your login credentials secure</li>
        <li>You are responsible for API keys, bot tokens, and database URLs you configure</li>
        <li>You must provide accurate registration information</li>
        <li>One person or organization may not abuse the service or attempt unauthorized access</li>
      </ul>

      <h2>4. Acceptable use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Use AYRA for illegal activity, spam, harassment, or fraud</li>
        <li>Post content via X or Telegram that violates platform rules or applicable law</li>
        <li>Attempt to bypass rate limits, encryption, or tenant isolation</li>
        <li>Run agents that impersonate others or spread misinformation at scale</li>
        <li>Use the platform to provide unlicensed financial advice or guaranteed investment returns</li>
        <li>Reverse-engineer or attack the service in bad faith</li>
      </ul>

      <h2>5. AI-generated output</h2>
      <p>
        Agent responses are generated by third-party language models and tools. Outputs may be
        inaccurate, incomplete, or outdated. You are solely responsible for reviewing agent output
        before publishing, posting, or acting on it — especially for on-chain research and social
        media content.
      </p>

      <h2>6. Not financial advice</h2>
      <p>
        AYRA Agent provides developer tooling and research helpers. Nothing on the platform
        constitutes financial, investment, legal, or tax advice. Token research skills are for
        informational and development purposes only. Always do your own research (DYOR).
      </p>

      <h2>7. Third-party services</h2>
      <p>
        Your use of OpenRouter, X, Telegram, Solana RPC providers, and database hosts is subject
        to their respective terms. AYRA is not responsible for outages, policy changes, or costs
        imposed by third parties.
      </p>

      <h2>8. Self-hosted deployments</h2>
      <p>
        If you deploy AYRA Agent yourself, you are the operator and data controller for your
        instance. You must secure your environment, rotate secrets, and comply with privacy laws
        applicable to your users.
      </p>

      <h2>9. Intellectual property</h2>
      <p>
        AYRA Agent software is released under the MIT License. The AYRA brand, logo, and character
        assets remain the property of their respective owners. You retain ownership of content you
        create through agents.
      </p>

      <h2>10. Disclaimer of warranties</h2>
      <p>
        THE SERVICE IS PROVIDED &quot;AS IS&quot; WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED,
        INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. WE DO
        NOT WARRANT UNINTERRUPTED OR ERROR-FREE OPERATION.
      </p>

      <h2>11. Limitation of liability</h2>
      <p>
        TO THE MAXIMUM EXTENT PERMITTED BY LAW, AYRA AGENT AND ITS CONTRIBUTORS SHALL NOT BE LIABLE
        FOR INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF
        PROFITS, DATA, OR GOODWILL, ARISING FROM YOUR USE OF THE SERVICE.
      </p>

      <h2>12. Termination</h2>
      <p>
        We may suspend or terminate access for violations of these terms. You may delete your
        account at any time from Settings. Upon termination, your platform account data may be
        removed; data in your private Postgres remains under your control.
      </p>

      <h2>13. Changes</h2>
      <p>
        We may update these terms. Continued use after changes constitutes acceptance. Check the
        &quot;Last updated&quot; date for the current version.
      </p>

      <h2>14. Contact</h2>
      <p>
        Questions: email <a href="mailto:support@ayra.run">support@ayra.run</a>, use{" "}
        <a href="https://ayra.run/support" target="_blank" rel="noopener noreferrer">
          AYRA CS Support
        </a>
        ,{" "}
        <a href="https://x.com/Ayradotrun" target="_blank" rel="noopener noreferrer">
          @Ayradotrun
        </a>
        , or{" "}
        <a href="https://github.com/ayradotrun/ayra-agent/issues" target="_blank" rel="noopener noreferrer">
          GitHub Issues
        </a>
        .
      </p>
    </LegalPageLayout>
  );
}
